---
- name: "Create IMM Pools"
  vars:
    api_info: &api_info_org_moid
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  cisco.intersight.intersight_rest_api:
    <<: *api_info_org_moid
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ org_name }}'"
  register: intersight_org
  delegate_to: localhost
  tags: always
  run_once: true

- name: Create IP Pool for In-Band and Out-of-Band Management
  ansible.builtin.include_tasks: create_ip_pools.yml

- name: Create MAC Pools for FI-A and FI-B
  ansible.builtin.include_tasks: create_mac_pools.yml

- name: Create UUID Pool
  ansible.builtin.include_tasks: create_uuid_pool.yml

- name: Create IQN pool only if if "configure_iscsi = true" 
  ansible.builtin.include_tasks: create_iqn_pools.yml
  when: configure_iscsi == 'true'

- name: Create iSCSI IP pools only if "configure_iscsi = true"
  ansible.builtin.include_tasks: create_iscsi_pools.yml
  when: configure_iscsi == 'true'

- name: Create FC WWN and WWPN pools only if "configure_fc=true"
  ansible.builtin.include_tasks: create_fc_ww_pools.yml
  when: configure_fc == 'true'

